---
- name: Ensure nmap is installed
  package:
    name: nmap
    state: present

- name: Ensure htop is installed
  package:
    name: htop
    state: present

- name: Ensure Vim is installed
  package:
    name: vim
    state: present

- name: Ensure Git is installed
  package:
    name: git
    state: present

- name: Ensure FZF is installed
  package:
    name: fzf
    state: present
- name: Ensure FZF keybindings are activated
  lineinfile:
    path: /etc/profile
    line: source /usr/share/doc/fzf/examples/key-bindings.bash

- name: Ensure LC_ALL is set
  lineinfile:
    path: /etc/profile
    line: export LC_ALL="en_US.UTF-8"

- name: Ensure CPU temp script is present
  copy:
    src: roles/basetools/files/cputemp
    dest: /bin/cputemp
    owner: root
    group: root
    mode: '0755'

- name: Ensure tree is installed
  package:
    name: tree
    state: present

- name: Ensure Ripgrep is installed
  package:
    name: ripgrep
    state: present
