---
- name: Ensure nmap is installed
  package:
    name: nmap
    state: latest

- name: Ensure htop is installed
  package:
    name: htop
    state: latest

- name: Ensure Neovim is installed
  package:
    name: neovim
    state: latest

- name: Ensure Git is installed
  package:
    name: git
    state: latest

- name: Ensure FZF is installed
  package:
    name: fzf
    state: latest
- name: Ensure FZF keybindings are activated
  lineinfile:
    path: /etc/profile
    line: source /usr/share/doc/fzf/examples/key-bindings.bash

- name: Ensure LC_ALL is set
  lineinfile:
    path: /etc/profile
    line: export LC_ALL="en_US.UTF-8"

- name: Ensure CPU temp script is present
  copy:
    src: roles/basetools/files/cputemp
    dest: /bin/cputemp
    owner: root
    group: root
    mode: '0755'

- name: Ensure tree is installed
  package:
    name: tree
    state: latest

- name: Ensure Ripgrep is installed
  package:
    name: ripgrep
    state: latest

- name: Ensure main user has nvim aliased to 'e'
  lineinfile:
    path: /home/pi/.bashrc
    line: "alias e=nvim"
    owner: pi
    state: present
    insertafter: EOF
    create: True

- name: Ensure terminfo for Kitty is installed
  package:
    name: kitty-terminfo
    state: latest
