---
- name: Provision NAS
  hosts: nas
  become: true
  vars_files:
    - vars/mounts.yaml
  pre_tasks:
    - name: Ensure drives are mounted
      tags: mounts
      ansible.posix.mount:
        path: "{{ item.path }}"
        src: "{{ item.src }}"
        fstype: "{{ item.fstype }}"
        opts: "{{ item.opts }}"
        state: "{{ item.state }}"
        dump: "{{ item.dump }}"
        passno: "{{ item.passno }}"
      loop: "{{ mounts }}"
    - name: Set facts for Jellyfin dirs
      set_fact:
        jellyfin_media_dir: "{{ mount_paths['media'] }}"
        jellyfin_cache_dir: "{{ mount_paths['cache'] }}"
  vars:
    jellyfin_repo_key_url: "https://repo.jellyfin.org/debian/jellyfin_team.gpg.key"
    jellyfin_repo_url: "https://repo.jellyfin.org/debian"
  roles:
    - role: basetools
      tags: basetools
    - role: fileserver
      tags: fileserver
    - role: webserver
      tags: webserver
    - role: torrentclient
      tags: torrentclient
    - role: mediaserver
      tags: mediaserver
