---
- hosts: servers
  become: true
  roles:
    - role: basetools
      tags: basetools
    - role: torrentclient
      tags: torrentclient
    - role: fileserver
      tags: fileserver
    - role: webserver
      tags: webserver
