---
- name: Ensure Samba is installed
  package:
    name: samba
    state: present

- name: Samba configuration
  ansible.builtin.template:
    src: smb.conf.j2
    dest: "{{ samba_config }}"
    validate: "testparm -s %s"
    mode: '0644'
  notify: Restart Samba
