---
- ansible.builtin.name: Ensure Samba is installed
  package:
    name: samba
    state: latest

- ansible.builtin.name: Ensure Samba is running
  service:
    name: smbd
    enabled: true
    state: started
